name = "following-sync"
main = "index.ts"
compatibility_date = "2024-01-15"
dev.port = 3000
[vars]
FREEMYX_API_URL = "https://freemyx.com"

[durable_objects]
bindings = [
  { name = "DORM_NAMESPACE", class_name = "DORM" }
]

[[migrations]]
tag = "v1"
new_sqlite_classes = ["DORM"]

[triggers]
crons = ["0 6 * * *"] # Daily at 6 AM UTC
