name = "xysql-followings"
main = "main.ts"
compatibility_date = "2025-06-06"

dev.port = 3000
routes = [
  { pattern = "followings.xysql.com", custom_domain = true }
]

[triggers]
crons = ["0 6 * * *"]

[[durable_objects.bindings]]
name = "DORM_NAMESPACE"
class_name = "DORM"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["DORM"]
